# Generated by Django 4.2.16 on 2024-09-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('marks', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cv',
            name='education',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='skills',
        ),
        migrations.AddField(
            model_name='cv',
            name='educations',
            field=models.ManyToManyField(to='cv.education'),
        ),
        migrations.AddField(
            model_name='cv',
            name='experiences',
            field=models.ManyToManyField(to='cv.experience'),
        ),
        migrations.AddField(
            model_name='cv',
            name='skills',
            field=models.ManyToManyField(to='cv.skill'),
        ),
    ]
