# Generated by Django 4.2.16 on 2024-09-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_education_experience_skill_remove_cv_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='phone',
        ),
    ]
