# Generated by Django 4.2.16 on 2024-09-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_remove_cv_email_remove_cv_name_remove_cv_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='institution_name',
            new_name='name',
        ),
    ]
